#!/bin/bash
#mostrar el elemento del array dado en el segundo parametro
#array1=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
array1=$1
array2=$2

function find_array {
  for ((i=0;i<${#array2[@]};i=i+1));do
    for((j=0;j<${#array1[@]};j=j+1));do
      if [ ${array2[i]} -eq $j ];then
        echo -n "${array1[j]} "
      fi
    done
  done
echo
}
find_array $1 $2
