#!/bin/bash
#determinar el mayor de 3 valores
if [ $# -ne 3 ];then
  echo Introduce 3 valores
else
  if [ $1 -gt $2 ] && [ $1 -gt $3 ]; then
    echo $1
  elif [ $2 -gt $1 ] && [ $2 -gt $3 ]; then
    echo $2
  else
    echo $3
  fi
fi
